=== daechu5657/qubbi/packages/sdk-builder/schema/cli.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": ["appModule", "swagger", "appModuleExport", "exportPackageName"],
  "additionalProperties": false,
  "properties": {
    "$schema": { "type": "string" },
    "appModule": { "type": "string" },
    "appModuleExport": { "type": "string" },
    "exportPackageName": { "type": "string" },
    "swagger": {
      "type": "object",
      "additionalProperties": false,
      "required": ["openapi", "info"],
      "properties": {
        "openapi": { "type": "string", "enum": ["2.0", "3.0", "3.1", "3.2"] },
        "info": {
          "type": "object",
          "additionalProperties": false,
          "required": ["title", "description", "version"],
          "properties": {
            "title": { "type": "string" },
            "description": { "type": "string" },
            "version": { "type": "string" }
          }
        }
      }
    }
  }
}

=== daechu5657/qubbi/apps/server/sdk-cli.json
{
  "$schema": "./node_modules/@qubbi/sdk-cli/schema/cli.json",
  "appModule": "./dist/app.module.js",
  "appModuleExport": "AppModule",
  "exportPackageName": "@qubbi/sdk",
  "swagger": {
    "openapi": "3.1",
    "info": {
      "title": "API",
      "description": "The API description",
      "version": "1.0"
    }
  }
}
